name: Manual workflow
on:
  push:
    branches: main
#   workflow_dispatch:
#     inputs:
#       name:
#         description: 'Person to greet'
#         default: 'World'
#         required: true

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    
    - run: |
        deno eval "console.log(1+1)"
    
    - name: Run bundler
      run: sh bundle_frontend.sh
    
    - name: Archive tar
      run: tar -czf frontend-dist.tar.gz frontend-dist
      
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: frontend-dist.tar.gz
      
    - name: View context attributes
      uses: actions/github-script@v6
      with:
        script: |
          console.log(context)
          
    - name: Create release
      id: release
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.PAT_TOKEN}}
        script: |
          conts fs = require('fs');
          
          let create_result = await github.rest.repos.createRelease({
            owner: "fonsp",
            repo: "js-julia-artifacts-test-2",
            tag_name: `hello-from-${context.sha}`,
          })
          console.log(create_result)
          
          let upload_result = await github.rest.repos.uploadReleaseAsset({
            url: create_result.data.upload_url,
            headers: {
              "content-type": "application/gzip"
            },
            data: fs.createReadStream(`frontend-dist.tar.gz`),
            name: `frontend-dist.tar.gz`,
          });
          console.log(upload_result)
