name: Manual workflow
on:
  push:
    branches: main
#   workflow_dispatch:
#     inputs:
#       name:
#         description: 'Person to greet'
#         default: 'World'
#         required: true

# permissions:
#   actions: write
#   checks: write
#   contents: write
#   deployments: write
#   id-token: write
#   issues: write
#   discussions: write
#   packages: write
#   pages: write
#   pull-requests: write
#   repository-projects: write
#   security-events: write
#   statuses: write

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Run bundler
      run: sh bundle_frontend.sh
    
    - name: Archive tar
      run: tar --mtime='1970-01-01 00:00:00' --sort=name --numeric-owner -czf frontend-dist.tar.gz frontend-dist
      
    - name: SHA256 hash
      id: sha256
      run: |
        echo "::set-output name=result::$(sha256sum frontend-dist.tar.gz | awk '{ print $1 }')\n"
    
    - run: echo ${{ steps.sha256.outputs.result }}
    
    - uses: actions/upload-artifact@v2
      with:
        path: frontend-dist.tar.gz
      
#     - name: View context attributes
#       uses: actions/github-script@v6
#       with:
#         script: |
#           console.log(context)
          
    - name: Create release
      id: release
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.PAT_TOKEN}}
        script: |
          const fs = require('fs');
          
          let create_result = await github.rest.repos.createRelease({
            owner: "fonsp",
            repo: "js-julia-artifacts-test-2",
            tag_name: `hello-from-${context.sha}`,
          })
          
          let upload_result = await github.rest.repos.uploadReleaseAsset({
            url: create_result.data.upload_url,
            headers: {
              "content-type": "application/gzip"
            },
            data: fs.readFileSync(`frontend-dist.tar.gz`),
            name: `frontend-dist.tar.gz`,
          });
          
          return upload_result.data.browser_download_url
        result-encoding: string

    - uses: julia-actions/setup-julia@v1
      with:
        version: '1.7'
    
    - run: git reset --hard
    - name: Update Artifacts.toml
      env:
        download_url: ${{ steps.release.outputs.result }}
      run: |
        julia -e '
        import Pkg
        Pkg.add([
          Pkg.PackageSpec(name="ArtifactUtils", version="0.2.1"),
          # Pkg.PackageSpec(name="JSON", version="0.21.3"),
          # Pkg.PackageSpec(name="GitHubActions", version="0.1.4"),
        ])
        using ArtifactUtils
        artifact_url = ENV["download_url"]
        
        add_artifact!(
            "Artifacts.toml",
            "bundle",
            @show(artifact_url),
            force=true,
        )
        '

    - uses: fregante/setup-git-user@v1
    - name: Push new Artifacts.toml to main
      run: |
          git add Artifacts.toml
          git commit -m "$GITHUB_WORKFLOW" -m "Built from hash $GITHUB_SHA"
          git push origin main